config/routes.rb
Rails.application.routes.draw do
  resources :courses
  root 'pages#home'
  get 'pages/about'
  get 'pages/location'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	def star_number
		self.star.blank? ? 1 : self.star
	end

	def cover
		self.image.blank? ? "default.png" : self.image
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:image, :video, :title, :star, :description, :public)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def location
  end

  def home
  	@courses = Course.where(public: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :image, placeholder: "Image" %>
  </div>

  <div class="field">
    <%= form.text_field :video, placeholder: "Video" %>
  </div>

  <div class="field">
    <%= form.text_field :title, placeholder: "Title" %>
  </div>

  <div class="field">
    <%= form.number_field :star, placeholder: "Stars" %>
  </div>

  <div class="field">
    <%= form.text_area :description, placeholder: "Description", length: "800", class: "materialize-textarea" %>
  </div>

  <div class="field">

    <%= form.check_box :public, id: :public, class: "filled-in" %>
    <label for="public">Public</label>
  </div>  

<button class="btn green darken-1" type="submit">Submit</button>
<%= link_to "Go to all courses",courses_path, class: "btn  green darken-2 white-text" %>

<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<%= link_to new_course_path, class: "btn-floating btn-large waves-effect waves-light green darken-1"  do %>
  <i class="material-icons">add</i>
<% end %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th ></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.title, course %></td>
        <td>
          <%= link_to edit_course_path(course) do %>
            <i class="material-icons">edit</i>
          <% end %>
          <%= link_to course, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="material-icons">delete</i>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

app/views/courses/show.html.erb
 <div class="row">
    <div class="col s12">
      <div class="card blue-grey darken-1">
        <div class="card-image">
          <div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><iframe src="https://fast.wistia.net/embed/iframe/<%= @course.video %>" title="Borrowed video: Welcome to Wistia!" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="100%" height="100%"></iframe></div></div>
<script src="https://fast.wistia.net/assets/external/E-v1.js" async></script>
        </div>
        <div class="card-content white-text">
          <div class="row">
            <div class="col m4 center">
              <%= image_tag "Courses/#{@course.cover}" %>
            </div>
            <div class="col m8">
              <span class="card-title"><%= @course.title %> </span>
              <% (1..@course.star_number).each do %>
                <i class="material-icons">grade</i>
              <% end %>
              <p> <%= @course.description %> </p>  
            </div>
          </div>
          
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleUdemy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">


    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
   
  </head>

  <body>

  <nav>
    <div class="nav-wrapper green darken-1">
      <a href="<%= root_path %>" class="brand-logo">Udemo</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
      <li><a href="<%= courses_path %>">Courses</a></li>
      <li><a href="<%= pages_about_path %>">About</a></li>
      <li><a href="<%= pages_location_path %>">Location</a></li>
      </ul>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <li><a href="<%= courses_path %>">Courses</a></li>
    <li><a href="<%= pages_about_path %>">About</a></li>
    <li><a href="<%= pages_location_path %>">Location</a></li>
  </ul>
<div class="row">
  <div class="col m10 offset-m1">
    <%= yield %>
  </div>
</div>



    <script>
    document.addEventListener('DOMContentLoaded', function() {
      var elems = document.querySelectorAll('.sidenav');
      var instances = M.Sidenav.init(elems, options);
    });
  
    </script>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About</h2>

<div class="card z-depth-3">
	
	<div class="card-content white-text">
		<div class="row">
			
			<div class="col m6">
				<a class="twitter-timeline" data-height="400" href="https://twitter.com/elvis_ozoria?ref_src=twsrc%5Etfw">Tweets by elvis_ozoria</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

			</div>

			<div class="col m6">
				
				<div class="card-panel teal ligther-1 z-depth-1">
					<div class="row">
						<div class="col m3">
							
							<%= image_tag "bl-logo.jpg", class: "circle responsive-img" %>
						</div>
						<div class="col m9">
							<span class="white-tetx">
								<h5> holaaa!</h5>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
								tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
								quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
								consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
								cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
								proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
							</span>

						</div>
					</div>
				</div>
			</div>


		</div>
	</div>
</div>

app/views/pages/home.html.erb
<br>

<div class="row">
	<% @courses.each do |course| %>
		<div class="col m4">
			<div class="card">
				<div class="card-image">
					<%= link_to course do %>
						<%= image_tag "Courses/#{course.cover}" %>
              		<% end %>
				</div>
				<div class="card-content">
					<span class="card-title"><%= course.title %> </span>
	              	<% (1..course.star_number).each do %>
	                <i class="material-icons green-text">grade</i>
	              	<% end %>
              	</div>
			</div>
		</div>
	<%  end %>

</div>

app/views/pages/location.html.erb
<h2>Location</h2>

<div class="card z-depth-3">
	<div class="card-content dark-text">
		<div class="row">
			You can find me here: </br>
			<iframe width="100%" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=place_id:EktDYWxsZSBKb2FxdcOtbiBNYXLDrWEgQm9iZWEsIFNhbiBQZWRybyBkZSBNYWNvcmlzIDIxMDAwLCBEb21pbmljYW4gUmVwdWJsaWMiLiosChQKEglZpfcGm2CvjhHzDWXZUu_YORIUChIJDaK7iJNgr44RxARd5PxCAVo&key=AIzaSyC_tl28sEOfHuL-PmtNWcFsGrEDknJ9geI" allowfullscreen></iframe>

		</div>
	</div>

</div>